import { THEME } from '../../../constants';

export default {
  '@keyframes aboutTitleEffect': {
    '0%': { color: 'transparent' },
    '50%': { color: 'transparent' },
    '70%': { color: THEME.colors.white },
    '100%': { color: THEME.colors.white },
  },
  '@keyframes aboutTitleBeforeEffect': {
    '0%': { width: 0, left: 0 },
    '35%': { width: '120%', left: 0 },
    '65%': { width: '120%', left: 0 },
    '100%': { width: 0, left: '120%' },
  },
  '@keyframes subTitleBeforeEffect': {
    '0%': { left: -100, opacity: 0 },
    '100%': { left: 0, opacity: 1 },
  },
  about: {
    maxWidth: 600,
    width: '32vw',
    minWidth: 470,
    marginTop: 35,
    height: '100%',
    display: 'flex',
    overflow: 'hidden',
    flexDirection: 'column',
    '&.animate': {
      '& $aboutTitle': {
        animation: '$aboutTitleEffect 1s linear 0.5s 1 forwards',
        '&:before': {
          animation: 'inherit',
          animationName: '$aboutTitleBeforeEffect',
        },
        '&:nth-child(2)': { animationDelay: '0.6s' },
        '&:nth-child(3)': { animationDelay: '0.7s' },
        '&:nth-child(4)': { animationDelay: '0.8s' },
      },
      '& $subTitle': {
        animation: '$subTitleBeforeEffect 0.5s linear 1.4s 1 forwards',
      },
    },
  },
  aboutTitle: {
    fontSize: 45,
    marginBottom: 10,
    cursor: 'default',
    fontWeight: 'bold',
    userSelect: 'none',
    letterSpacing: 0.5,
    color: 'transparent',
    width: 'max-content',
    position: 'relative',
    transition: THEME.transition,
    fontFamily: '"Lobster", cursive, Roboto, "sans-serif"',
    '&:before': {
      left: 0,
      width: 0,
      top: '50%',
      content: '""',
      height: '105%',
      display: 'block',
      position: 'absolute',
      transform: 'translateY(-50%)',
      backgroundColor: THEME.colors.white,
    },
  },
  subTitle: {
    opacity: 0,
    position: 'relative',
  },
  description: {
    fontSize: 30,
    fontWeight: 300,
    marginBottom: 48,
    cursor: 'default',
    userSelect: 'none',
    color: THEME.colors.white,
    '& strong:hover': {
      cursor: 'pointer',
      color: THEME.colors.pink,
      transition: THEME.transition,
    },
  },
  btnGroup: { display: 'flex', alignItems: 'center' },
  button: { maxWidth: 145, marginRight: 32 },
  btnText: {
    margin: 0,
    fontSize: 12,
    display: 'flex',
    cursor: 'pointer',
    fontWeight: 'bold',
    letterSpacing: 1.5,
    alignItems: 'center',
    color: THEME.colors.white,
    minWidth: 'max-content',
    textTransform: 'uppercase',
    transition: THEME.transition,
    '&:hover': { color: THEME.colors.pink },
  },
  [`@media (max-width: ${THEME.breakpoints.maxXXl}px)`]: {
    aboutTitle: { fontSize: 35 },
    description: { fontSize: 20 },
  },
  [`@media (max-width: ${THEME.breakpoints.maxMd}px)`]: {
    aboutTitle: { fontSize: 25 },
    description: { fontSize: 16, marginBottom: 32 },
    btnGroup: { transform: 'scale(0.7)', transformOrigin: 'top left' },
  },
  [`@media (max-width: ${THEME.breakpoints.maxSm}px)`]: {
    about: {
      width: 'calc(100vw - 40px)',
      minWidth: 'unset',
      maxWidth: 'unset',
    },
  },
};
