import { THEME } from '../../constants';

export default {
  '@keyframes aboutTitleEffect': {
    '0%': { color: 'transparent' },
    '50%': { color: 'transparent' },
    '70%': { color: THEME.color.black },
    '100%': { color: THEME.color.black },
  },
  '@keyframes aboutTitleBeforeEffect': {
    '0%': { width: 0, left: 0 },
    '35%': { width: '120%', left: 0 },
    '65%': { width: '120%', left: 0 },
    '100%': { width: 0, left: '120%' },
  },
  '@keyframes subTitleBeforeEffect': {
    '0%': { left: -100, opacity: 0 },
    '100%': { left: 0, opacity: 1 },
  },
  root: { padding: 60 },
  content: {
    // display: 'flex',
    // height: 'calc(100vh - 90px)',
  },
  about: { maxWidth: 600 },
  aboutTitle: {
    fontSize: 45,
    marginBottom: 10,
    cursor: 'default',
    fontWeight: 'bold',
    userSelect: 'none',
    letterSpacing: 0.5,
    color: 'transparent',
    width: 'max-content',
    position: 'relative',
    fontFamily: '"Lobster", cursive, Roboto, "sans-serif"',
    animation: '$aboutTitleEffect 1s linear 0.5s 1 forwards',
    '&:before': {
      top: '50%',
      content: '""',
      height: '105%',
      display: 'block',
      animation: 'inherit',
      position: 'absolute',
      transform: 'translateY(-50%)',
      backgroundColor: THEME.color.black,
      animationName: '$aboutTitleBeforeEffect',
    },
    '&:nth-child(2)': { animationDelay: '0.6s' },
    '&:nth-child(3)': { animationDelay: '0.7s' },
    '&:nth-child(4)': { animationDelay: '0.8s' },
  },
  subTitle: {
    position: 'relative',
    left: -600,
    opacity: 0,
    animation: '$subTitleBeforeEffect 0.5s linear 1.4s 1 forwards',
  },
  description: {
    fontSize: 30,
    fontWeight: 300,
    marginBottom: 48,
    cursor: 'default',
    userSelect: 'none',
    '& strong:hover': {
      cursor: 'pointer',
      color: THEME.color.pink,
      transition: THEME.transition,
    },
  },
  btnGroup: {
    display: 'flex',
    alignItems: 'center',
  },
  buton: {
    maxWidth: 145,
    marginRight: 32,
  },
  btnText: {
    margin: 0,
    fontSize: 12,
    display: 'flex',
    cursor: 'pointer',
    fontWeight: 'bold',
    letterSpacing: 1.5,
    alignItems: 'center',
    color: THEME.color.black,
    textTransform: 'uppercase',
    transition: THEME.transition,
    '&:hover': { color: THEME.color.pink },
  },
};
